# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Change this to be the correct version of Node.js
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          
      - name: Python Set Up
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9

      # Sets up npm environment 
      - name: npm install
        run: npm install

      # Runs a set of commands using the runners shell
      # This is how we will also install dependencies
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          
      - name: Test with pytest
        run: |
          pytest
          
      - name: Test with npm
        run: npm test
