# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Change this to be the correct version of Node.js
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          
      # Sets up npm environment 
      - name: Install dependencies
        run: npm ci
      - name: Build with npm
        run: npm run build --if-present
      - name: Test with npm
        run: npm test
          
      - name: Python Set Up
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        
      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 --ignore=E,W .
          
      - name: Test with pytest
        run: |
          pip install pytest
          pip install pytest-cov
          pytest tests.py --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
    
    # credentials to connect to AWS
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 
          profile_name: default 
          project_name: Echo
          runtime: python3.9
          
    # Zip functions to deploy to lambda
      - name: Zip functions
        run: |
          zip -r pull_song.zip ./pull_song_handler.py ./db_client.py ./exceptions.py
          zip -r pull_user.zip ./pull_user_handler.py ./db_client.py ./exceptions.py
          zip -r push.zip ./push_handler.py ./db_client.py ./exceptions.py
          
    # Deploy to AWS
      - name: AWS Lambda Deploy pull_song
        uses: appleboy/lambda-action@v0.0.4
        with:
            #name of my AWS Lambda Function
            function_name: pull_song
            #contains all the files for the lambda
            zip_file: pull_song.zip
      - name: AWS Lambda Deploy pull_account
        uses: appleboy/lambda-action@v0.0.4
        with:
            function_name: pull_account
            zip_file: pull_user.zip
      - name: AWS Lambda Deploy push
        uses: appleboy/lambda-action@v0.0.4
        with:
            function_name: push_data
            zip_file: push.zip
